esphome:
  name: esphome-web-998ec8
  includes:
    - veml7700_sensor.h
  libraries:
    - SPI
    - Wire
    - adafruit/Adafruit BusIO @ 1.9.6
    - "https://github.com/adafruit/Adafruit_VEML7700"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:



wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-998Ec8"
    password: "ls1vrzRHbsy9"

captive_portal:
    
i2c:
  sda: 21
  scl: 22
  scan: true
#  id: bus_a
  frequency: 10000 Hz
  
    
sensor:
  - platform: custom
    lambda: |-
      auto veml7700 = new VEML7700CustomSensor();
      App.register_component(veml7700);
      return {veml7700, veml7700->lux_sensor, veml7700->white_sensor, veml7700->als_sensor};
    sensors:
      name: "VEML7700 Light" # Required dummy sensor
      unit_of_measurement: Lux
      accuracy_decimals: 0
      name: "VEML770 White"
      unit_of_measurement: raw
      accuracy_decimals: 0
      name: "VEML770 ALS"
      unit_of_measurement: raw
      accuracy_decimals: 0
  - platform: sht3xd
    temperature:
      name: "Temp"
      unit_of_measurement: "°C"
      icon: "mdi:water-percent"
      state_class: "measurement"
      accuracy_decimals: 1
      id: temp_sensor
    humidity:
      name: "Humidity"
    address: 0x44
    update_interval: 10s
  - platform: adc
    pin: 34
    name: "Soil Moisture"
    update_interval: 6s
    unit_of_measurement: "%"
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 91 -> 0.00
        - 100 -> 100.00
    - lambda: 
        if (x < 0) return 0; 
        else if (x > 100) return 100;
        else return (x);
    accuracy_decimals: 0
    
binary_sensor:
  - platform: gpio
    pin:
      number: 16
      mode:
        input: true
        pullup: false
    name: "Presence"
    device_class: presence
    filters:
      - delayed_on_off: 10ms
  - platform: gpio
    pin:
      number: 17
      mode:
        input: true
    name: "Movement"
    device_class: motion
