esphome:
  name: esphome-web-radar-1


esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Abf2ec"
    password: "XtB9tpm6aSBQ"

# not sure what this is
captive_portal:



uart:
  - id: uart_1_id
    tx_pin: 14
    rx_pin: 27
    baud_rate: 256000
    parity: NONE
    stop_bits: 1
  - id: uart_2_id
    tx_pin: 26
    rx_pin: 25
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

ld2410:
  - uart_id: uart_1_id
    id: ld2410_1_id
    timeout: 5s
    max_move_distance : 6m
    max_still_distance: 4.5m
    g0_move_threshold: 10
    g0_still_threshold: 20
    g1_move_threshold: 10
    g1_still_threshold: 20
    g2_move_threshold: 20
    g2_still_threshold: 21
    g3_move_threshold: 30
    g3_still_threshold: 31
    g4_move_threshold: 40
    g4_still_threshold: 41
    g5_move_threshold: 50
    g5_still_threshold: 51
    g6_move_threshold: 60
    g6_still_threshold: 61
    g7_move_threshold: 70
    g7_still_threshold: 71
    g8_move_threshold: 80
    g8_still_threshold: 81
  - uart_id: uart_2_id
    id: ld2410_2_id
    timeout: 5s
    max_move_distance : 6m
    max_still_distance: 4.5m
    g0_move_threshold: 10
    g0_still_threshold: 20
    g1_move_threshold: 10
    g1_still_threshold: 20
    g2_move_threshold: 20
    g2_still_threshold: 21
    g3_move_threshold: 30
    g3_still_threshold: 31
    g4_move_threshold: 40
    g4_still_threshold: 41
    g5_move_threshold: 50
    g5_still_threshold: 51
    g6_move_threshold: 60
    g6_still_threshold: 61
    g7_move_threshold: 70
    g7_still_threshold: 71
    g8_move_threshold: 80
    g8_still_threshold: 81

sensor:
  - platform: ld2410
    ld2410_id: ld2410_1_id
    moving_distance:
      name : Moving Distance 1
    still_distance:
      name: Still Distance 1
    moving_energy:
      name: Move Energy 1
    still_energy:
      name: Still Energy 1
    detection_distance:
      name: Detection Distance 1

  - platform: ld2410
    ld2410_id: ld2410_2_id
    moving_distance:
      name : Moving Distance 2
    still_distance:
      name: Still Distance 2
    moving_energy:
      name: Move Energy 2
    still_energy:
      name: Still Energy 2
    detection_distance:
      name: Detection Distance 2

binary_sensor:
  - platform: ld2410
    ld2410_id: ld2410_1_id
    has_target:
      name: Presence 1
    has_moving_target:
      name: Moving Target 1
    has_still_target:
      name: Still Target 1
  - platform: ld2410
    ld2410_id: ld2410_2_id
    has_target:
      name: Presence 2
    has_moving_target:
      name: Moving Target 2
    has_still_target:
      name: Still Target 2

number:
  - platform: template
    id: max_move_distance
    name: "Max Move Distance"
    restore_value: true
    optimistic: true
    min_value: 0.75
    max_value: 6
    step: 0.75
    on_value:
      then:
        - lambda: |-
            id(uart_1_id).set_config_mode_(true);
            id(uart_1_id).set_max_move_distance(id(max_move_distance).state);
            id(uart_1_id).set_config_mode_(false);
            r24avd1::write_to_uart((uint8_t)r24avd1::FunctionCode::WRITE_COMMAND, (uint8_t)r24avd1::WriteAddressCode1::SYSTEM_PARAMETER, (uint8_t)r24avd1::AddressCode2::THRESHOLD_GEAR, b, 1, id(uart_id));
